### ISSUE TITLE
Why not a keyword?

### ISSUE THREAD

**Issue by TimoStaudinger** [jasnell/proposal-deprecated#4]
I'm sure there are good reasons why this is a terrible idea, but it something an approach like the following seems pretty ergonomic from a user's perspective:

```js
deprecated function foo() {
  console.log("I'm deprecated, don't call me!")
}

const bar = "I'm deprecated, don't import me!"
deprecated export default bar
```

Curious to hear why that this is not a viable approach, aside from the missing backwards compatibility without a compilation step?

**Comment by zloirock** [comment]
Since `deprecated` is a valid variable name?
```js
const deprecated = 42
const foo = deprecated
function bar() { /* ... */ }
// const foo = deprecated function bar() { /* ... */ }
```

**Comment by TimoStaudinger** [comment]
Fair point! However, so was `let`, until it wasn't, if I understand correctly.

Admittedly, it seems like `let` was added as a keyword with ES5, not just recently. Must have had much less of an impact back then.
